#!/usr/bin/env python3
"""
add_section.py

https://github.com/kevinpinscoe/how-I-make-books-now

Interactive helper to create a new Markdown section file under contents/<folder>
and append it to contents/manifest.txt.

Usage:
  python3 add_section.py
  # optional non-interactive usage:
  python3 add_section.py --dir chap03 --name "New subsection about walls"
  python3 add_section.py --dir zzzz-appendices --filename extra-notes.md
"""

import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path

CONTENTS_DIR = Path("contents")
MANIFEST_PATH = CONTENTS_DIR / "manifest.txt"
# Folders to ignore in the picker (you can add more if you like)
IGNORE_FOLDERS = {"images", ".git", "__pycache__"}

def slugify(title: str) -> str:
    """Convert a human title to a safe filename slug (lowercase, hyphens)."""
    s = title.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE)   # drop non-word chars
    s = re.sub(r"[\s_-]+", "-", s).strip("-")          # normalize separators
    return s or "untitled"

def is_valid_filename(name: str) -> bool:
    """Basic sanity check for filenames (no path separators, not empty)."""
    return bool(name) and "/" not in name and "\\" not in name

def list_target_dirs() -> list[Path]:
    """List candidate subdirectories under contents/."""
    if not CONTENTS_DIR.is_dir():
        print(f"ERROR: {CONTENTS_DIR} directory not found. Run from project root.", file=sys.stderr)
        sys.exit(1)
    dirs = [
        p for p in sorted(CONTENTS_DIR.iterdir())
        if p.is_dir() and p.name not in IGNORE_FOLDERS and not p.name.startswith(".")
    ]
    return dirs

def pick_directory(dirs: list[Path]) -> Path:
    print("Pick a target folder under contents/:\n")
    for i, d in enumerate(dirs, start=1):
        print(f"  {i:2d}) {d.name}/")
    print()
    raw = input("Enter number or type folder name: ").strip()
    # number?
    if raw.isdigit():
        idx = int(raw)
        if 1 <= idx <= len(dirs):
            return dirs[idx - 1]
        print("Invalid number. Aborting.", file=sys.stderr)
        sys.exit(2)
    # name?
    candidates = [d for d in dirs if d.name == raw]
    if candidates:
        return candidates[0]
    print(f"Folder '{raw}' not found under contents/. Aborting.", file=sys.stderr)
    sys.exit(2)

def ensure_manifest_exists():
    """Create an empty manifest if missing (keeps your sed filters happy)."""
    if not MANIFEST_PATH.exists():
        MANIFEST_PATH.write_text("# Manifest autogenerated\n", encoding="utf-8")

def append_to_manifest(entry: str):
    """Append a line to manifest if it doesn't already exist (exact match)."""
    ensure_manifest_exists()
    existing = MANIFEST_PATH.read_text(encoding="utf-8").splitlines()
    if entry in existing:
        print(f"Manifest already contains:\n  {entry}")
        return
    with MANIFEST_PATH.open("a", encoding="utf-8") as f:
        f.write(entry + "\n")
    print(f"Appended to manifest:\n  {entry}")

def normalize_filename(section_input: str) -> tuple[str, str]:
    """
    Accept either a human title ('New Section') or a filename ('new-section.md').
    Returns (filename, title_for_heading).
    """
    if section_input.lower().endswith(".md") and is_valid_filename(section_input):
        filename = section_input
        title_guess = re.sub(r"\.md$", "", filename, flags=re.IGNORECASE)
        title_guess = title_guess.replace("-", " ").strip().title()
        return filename, title_guess
    # treat as title -> slug + .md
    slug = slugify(section_input)
    return f"{slug}.md", section_input.strip()

def write_markdown_stub(path: Path, title: str):
    """
    Create a minimal markdown file with a '## ' heading and a timestamp comment.
    """
    if path.exists():
        print(f"ERROR: File already exists: {path}", file=sys.stderr)
        sys.exit(3)
    header = f"## {title}\n\n"
    stamp = f"<!-- Created {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} by add_section.py -->\n\n"
    path.write_text(stamp + header, encoding="utf-8")
    print(f"Created: {path}")

def main():
    parser = argparse.ArgumentParser(description="Create a new Markdown section and append it to manifest.")
    parser.add_argument("--dir", help="Target folder under contents/ (e.g., chap03, zzzz-appendices)")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--name", help="Human section title (will be slugified to filename)")
    group.add_argument("--filename", help="Exact filename to create (e.g., this-is-the-section-name.md)")
    args = parser.parse_args()

    dirs = list_target_dirs()

    if args.dir:
        target = next((d for d in dirs if d.name == args.dir), None)
        if not target:
            print(f"ERROR: Folder '{args.dir}' not found under contents/.", file=sys.stderr)
            sys.exit(2)
    else:
        target = pick_directory(dirs)

    if args.filename:
        filename, title = normalize_filename(args.filename)
    elif args.name:
        filename, title = normalize_filename(args.name)
    else:
        section_input = input("Enter section title (or filename ending in .md): ").strip()
        if not section_input:
            print("No name provided. Aborting.", file=sys.stderr)
            sys.exit(2)
        filename, title = normalize_filename(section_input)

    if not filename.lower().endswith(".md"):
        filename += ".md"

    if not is_valid_filename(filename):
        print(f"ERROR: Invalid filename: {filename}", file=sys.stderr)
        sys.exit(2)

    new_file_path = target / filename

    # Create the file with a markdown stub
    write_markdown_stub(new_file_path, title)

    # Append to manifest as 'contents/<folder>/<file>.md'
    manifest_entry = f"{CONTENTS_DIR.as_posix()}/{target.name}/{filename}"
    append_to_manifest(manifest_entry)

    print("\nDone. You can reorder the new entry in contents/manifest.txt as needed.")

if __name__ == "__main__":
    main()
